### ISSUE TITLE
MenuEditor.py:481:__getPath:AttributeError: 'NoneType' object has no attribute 'root'

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mozo#23]
from dowstream report:
https://bugzilla.redhat.com/show_bug.cgi?id=1223048
```
 Logan Donovan 2015-05-19 12:51:06 EDT

Version-Release number of selected component:
mozo-1.8.0-2.fc21

Additional info:
reporter:       libreport-2.3.0
cmdline:        /usr/bin/python2.7 -OOt /usr/bin/mozo
executable:     /usr/bin/mozo
kernel:         3.19.7-200.fc21.x86_64
runlevel:       N 5
type:           Python
uid:            1000

Truncated backtrace:
MenuEditor.py:481:__getPath:AttributeError: 'NoneType' object has no attribute 'root'

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Mozo/MainWindow.py", line 432, in on_item_tree_show_toggled
    self.editor.setVisible(item, False)
  File "/usr/lib/python2.7/site-packages/Mozo/MenuEditor.py", line 201, in setVisible
    menu_xml = self.__getXmlMenu(self.__getPath(item.get_parent()), dom, dom)
  File "/usr/lib/python2.7/site-packages/Mozo/MenuEditor.py", line 481, in __getPath
    path = menu.tree.root.get_menu_id()
AttributeError: 'NoneType' object has no attribute 'root'

Local variables in innermost frame:
path: None
self: <Mozo.MenuEditor.MenuEditor instance at 0x7fd380047170>
menu: <matemenu.Directory object at 0x7fd3833ecac8>
```
stacktrace:
https://bugzilla.redhat.com/attachment.cgi?id=1027315

**Comment by monsta** [comment]
Downstream report is EOL and there were no further reports or comments...
