### ISSUE TITLE
Mozo-gtk3 in arch linux not start.

### ISSUE THREAD

**Issue by croutch** [mate-desktop/mozo#25]
Hello.

I got this error in terminal when starting mozo-gtk3.

 mozo
Traceback (most recent call last):
  File "/usr/bin/mozo", line 22, in <module>
    from Mozo.MainWindow import MainWindow
  File "/usr/lib/python2.7/site-packages/Mozo/MainWindow.py", line 20, in <module>
    import gi
ImportError: No module named gi

**Comment by croutch** [comment]
I found the solution.
In testing package they have python-gobject,but should be python2-gobject.
After installed python2-gobject all works like it should.
sorry for the noice.
