### ISSUE TITLE
Mozo crashed on adding and removing Separator item

### ISSUE THREAD

**Issue by N0rbert** [mate-desktop/mozo#80]
#### Expected behaviour

* new separator item was created, user is able to delete it

#### Actual behaviour

* new separator item was created, shows the following error output in the terminal after clicking on it and trying to delete it:

```
$ mozo 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 91, in menuChanged
    self.loadUpdates()
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 102, in loadUpdates
    if iter and items[iter][3].get_desktop_file_path():
AttributeError: 'TreeSeparator' object has no attribute 'get_desktop_file_path'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 91, in menuChanged
    self.loadUpdates()
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 102, in loadUpdates
    if iter and items[iter][3].get_desktop_file_path():
AttributeError: 'TreeSeparator' object has no attribute 'get_desktop_file_path'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 91, in menuChanged
    self.loadUpdates()
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 102, in loadUpdates
    if iter and items[iter][3].get_desktop_file_path():
AttributeError: 'TreeSeparator' object has no attribute 'get_desktop_file_path'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 91, in menuChanged
    self.loadUpdates()
  File "/usr/lib/python3/dist-packages/Mozo/MainWindow.py", line 102, in loadUpdates
    if iter and items[iter][3].get_desktop_file_path():
AttributeError: 'TreeSeparator' object has no attribute 'get_desktop_file_path'

```

#### Steps to reproduce the behaviour

1. Install Ubuntu MATE 21.04 alpha
2. Launch Main Menu from the terminal with `mozo`
3. Place cursor on any menu item, click *New Separator*
4. Click on just created separator item to remove it with *Delete*

#### MATE general version

1.24.1

#### Package version

1.24.0-1

#### Linux Distribution

Ubuntu MATE 21.04

#### Link to bugreport of your Distribution (requirement)

https://bugs.launchpad.net/ubuntu/+source/mozo/+bug/1864445 since Ubuntu MATE 20.04 LTS

**Comment by lukefromdc** [comment]
I can confirm this on recent git master. Note that some of the time in my test the separator actually was removed from the menu though this is not displayed in Mozo, and sometimes it wasn't removed at all
